events {}

http {
    log_format json escape=json
      '{'
        '"time":"$time_iso8601",'
        '"method":"$request_method",'
        '"uri":"$uri",'
        '"status":$status,'
        '"body_bytes":$body_bytes_sent,'
        '"response_time":$request_time,'
        '"benchmark_run_id":"$http_x_benchmark_run_id"'
      '}';

    access_log /var/log/nginx/access.log json;

    server {
        listen 80;
        server_name _;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /status {
            stub_status;
            access_log off;
        }
    }
}
