[package]
name = "try-wasip2"
version = "0.1.0"
edition = "2024"

[dependencies]
wit-bindgen = "0.36.0"
wit-bindgen-rt = { version = "0.44.0", features = ["bitflags"] }

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = false
lto = true

[lib]
crate-type = ["cdylib"]
