/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.openrewrite.rewrite") version "latest.release"
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))

    rewrite(project(":paths-get-to-path-of"))
}

rewrite {
    activeRecipe("com.yourorg.java.migrate.PathsGetToPathOf")
    exclusion("**/*.gradle.kts")
    exclusion("**/build/**")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
