name: test diagram
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `\n
            \`\`\`stl
            solid cube_corner
            facet normal 0.0 -1.0 0.0
                outer loop
                vertex 0.0 0.0 0.0
                vertex 1.0 0.0 0.0
                vertex 0.0 0.0 1.0
                endloop
            endfacet
            facet normal 0.0 0.0 -1.0
                outer loop
                vertex 0.0 0.0 0.0
                vertex 0.0 1.0 0.0
                vertex 1.0 0.0 0.0
                endloop
            endfacet
            facet normal -1.0 0.0 0.0
                outer loop
                vertex 0.0 0.0 0.0
                vertex 0.0 0.0 1.0
                vertex 0.0 1.0 0.0
                endloop
            endfacet
            facet normal 0.577 0.577 0.577
                outer loop
                vertex 1.0 0.0 0.0
                vertex 0.0 1.0 0.0
                vertex 0.0 0.0 1.0
                endloop
            endfacet
            endsolid
            \`\`\``;
            await core.summary
              .addHeading('STL Diagram')
              .addRaw(output)
              .write()
